[package]
name = "hmp"
version = "0.1.0"
edition = "2018"

[dependencies]
reqwest = { version = "0.11.0", features = ["json", "cookies"] }
serde = "1.0.111"
serde_derive = "1.0.111"
serde_json = "1.0.55"
percent-encoding = "2.1.0"
